### ISSUE TITLE
drop-down 组件 width 属性无效

### ISSUE THREAD

**Issue by xiaoda** [51idc/anchor-design#3]
截图：
![qq20170717-104928](https://user-images.githubusercontent.com/2784806/28254247-a4bcf96e-6add-11e7-9796-4314335cbce6.png)
属性：
![qq20170717-104905](https://user-images.githubusercontent.com/2784806/28254248-aa16ddbc-6add-11e7-9752-24c234050ca6.png)

**Comment by ethanliu9527** [comment]
已修复
