### ISSUE TITLE
drop-down 组件当 defaultText 或默认选中项的文字较短时，下拉框中的文字被省略

### ISSUE THREAD

**Issue by xiaoda** [51idc/anchor-design#4]
截图：
![qq20170717-105128](https://user-images.githubusercontent.com/2784806/28254290-14c80942-6ade-11e7-8c9c-4915a4599f53.png)

另外这个地方的逻辑值得商榷，我认为下拉框的默认宽度应取决于 defaultText、下拉框文字的最长值，且在选择时不再改变。目前的交互略有些奇怪，建议作者大大体验一下再做决定~

**Comment by ethanliu9527** [comment]
目前组件的逻辑是：下拉列表中的最小宽度等于默认框宽度，最大宽度等于列表中最长的那条数据的宽度；默认框宽度设计为可自定义宽度，默认值为120px。这样能够保证列表数据总能显示出来。因此列表数据不会出现省略，截图属于bug，但是我并未重现。如果你再次重现，请帮忙修复。

**Comment by ethanliu9527** [comment]
bug 已重现，已解决
